### PR TITLE
Update menus.json

### PR DESCRIPTION
**Pull request by DDinghoya**
And, When I thought about it, Directory name is wrong by HOS localizations.

locale

Directory rename from "kr-KO" to "ko", Can you change it to "ko"?

Or should I delete the directory and create a new one?

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
Does it not currently work? 
Borealis expects `ko` (https://github.com/natinusala/borealis/wiki/Internationalization-system). If you get the app in Korean then I wouldn't change anything

**Comment by DDinghoya** [comment]
> Does it not currently work? Borealis expects `ko` (https://github.com/natinusala/borealis/wiki/Internationalization-system). If you get the app in Korean then I wouldn't change anything

I thought about it because I couldn't apply Korean until now.

nxlocaleswitcher

Of course, I thought in addition to the reason for the missing quotation marks.

I hope this FR solves it well.

**Comment by DDinghoya** [comment]
> Does it not currently work? Borealis expects `ko` (https://github.com/natinusala/borealis/wiki/Internationalization-system). If you get the app in Korean then I wouldn't change anything

It was confirmed that the Korean language was output normally only when the directory was converted to "ko" as below;

nxlocaleswitch_1

Would you please change from "kr-KO" to "ko"?

**Comment by HamletDuFromage** [comment]
oh sorry I misread you, I thought that you wanted to change from ko to kr-KO, not that what you wrote was in kr-KO

**Comment by DDinghoya** [comment]
> oh sorry I misread you, I thought that you wanted to change from ko to kr-KO, not that what you wrote was in kr-KO

Thank you! :)

**Pull request merged**
